Upgrade to colorful 0.5.4
Also ensure we only pass strings to colorful otherwise it fails.
TypeError: __str__ returned non-string (type int)

Test output slightly changed due to new colorful.
Writing \n instead of ^M.